# Generated by Django 4.1.7 on 2023-03-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_car_image_alter_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(null=True, upload_to='cars/'),
        ),
    ]
