# Generated by Django 4.1.7 on 2023-03-08 10:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_offer_image_height_offer_image_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=''),
        ),
    ]
